name: Build Wasm

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --version 0.2.126

      - name: Build WASM package
        run: |
          cargo build --manifest-path rust-fuzzy/Cargo.toml --target wasm32-unknown-unknown --release
          wasm-bindgen rust-fuzzy/target/wasm32-unknown-unknown/release/fuzzy_search.wasm --out-dir rust-fuzzy/pkg --target web

      - name: Upload wasm artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-package
          path: rust-fuzzy/pkg